name: conda-pkgdown

on:
  push:
    branches:
      - main

env:
  atoken: ${{ secrets.ANACONDA_UPLOAD_TOKEN }}
  recipe_path: conda/recipe
  env_path: conda/env

jobs:
  build-conda-deploy-pkgdown:
    # When merging to main and the commit message starts with 'Bump version:'
    if: "startsWith(github.event.head_commit.message, 'Bump version:')"
    name: Build conda package & deploy pkgdown website
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: 4.11.0-0
          show-channel-urls: true
          auto-activate-base: false
          activate-environment: condabuild
          environment-file: ${{ env.env_path }}/condabuild.yml
          use-mamba: true
      - name: Build + upload conda pkg
        run: |
          conda mambabuild ${recipe_path} -c umccr -c conda-forge -c bioconda --token ${atoken}
      - name: Install conda packages
        run: mamba env create -n pkgdown -f ${env_path}/pkgdown.yaml
      - name: Publish pkgdown website
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            conda activate pkgdown_gpgr
            printf "sigrap version:\n"
            Rscript -e "packageVersion('sigrap')"
            Rscript -e "pkgdown::deploy_to_branch(pkg = '.', commit_message = paste(pkgdown:::construct_commit_message('.'), '- see https://umccr.github.io/sigrap/'), branch = 'gh-pages', new_process = FALSE)"

